<!-- 
 HTML Outlook Signature File   						
 Created by C.Diphoorn Dec 2019 / May 2020
 TEMPLATE.TPL 10/12/2019	NB ** Ensure you modifiy this name to the same name as the file you have created.
 
 <*|ForceDefaultSignature|*True>
 <*|Debug|*True>
 <*|InternationalPrefix|*+61>	 
 <*|Company|*COMPANY NAME>
 <*|CompanyPhone|*07 5555 5555>	
 <*|CompanyFax|*>
 <*|CompanyURL|*www.URL.com.au>
 <*|DefaultCompany|*COMPANY NAME>
 <*|DefaultPOBox|*PO Box xxx, Brisbane>
 <*|DefaultPhone|*07 XXXX XXXX>	
 <*|DefaultAddress|*Unit 1, 24 Street ST, Suburb>
 <*|DefaultFax|*>
 <*|DefaultEmailDomain|*DOMAIN.COM.AU>	
 <*|DefaultWWW|*WWW.DOMAIN.com.au> 
 <*|ImageName|*SIGNATURE.png>
 <*|XmasFrom|*21/12/YYYY>
 <*|XmasTo|*09/01/YYYY>
 <*|XmasText|*Our office will be closed from 4.00pm on *|lastday|* We will be reopen at 8:30am on *|firstday|* with only sales staff operating from *|firstmonday|*.>
 <*|XmasHighlightColor|*#C67D5B>
 <*|XmasImageName|*SIGNATURE-Xmas.png>
 <*|ReplaceEmail|*@SIGNATURE.com.au, @OLDdomain.com.au>
 <*|FooterText|*SIGNATURE will be closed from COB *|lastday|*, reopening on *|firstday|*. We would like to take this opportunity to thank you for your continuing support during *|xmasstartyear|* and we look forward to working with you again in *|xmasfinishyear|*>
 
 <*|DefaultImageType|*png> 
 <*|AddPhoneSpace|*True>
 <*|AddAddressSpace|*True>
 <*|AddAdditionalAddressSpace|*True>
 <*|AddAdditionalStateSpace|*True>
 <*|AddAdditionalCitySpace|*False>
 <*|ForceCreate|*False>
 <*|ForceDefaultSignature|*False>
 <*|HideTableRows|*True>
 <*|AutoPOBox|*True> 
  
 <*|SocialIcon|*>									
 <*|SocialIconLink|*>
 
 <*|InsertHTML|*address>							
 <*|InsertHTMLFind|*char(10)>						
 <*|InsertHTMLCode|*'&nbsp;&nbsp;<span class="bar">|</span>&nbsp;&nbsp;'> 	
 
 <*|LinkWWWColor|*#DA0E28>
 <*|SymbolColor|*#DA0E28>
 <*|TextColor|*#7F7F7F>
 <*|TextColorHighlight|*#DA0E28>
 <*|TextFooterColor|*#00000>
 <*|BarColor|*#7F7F7F>
 <*|HyperLinkColor|*#7F7F7F>
 <*|DefaultFont|*"Arial", sans-serif>
 <*|DefaultFontSize|*10.0pt>
 
 <*|TransformState|*UPPER>
 <*|TransformMobile|*MOBILE>
 <*|TransformPhone|*PHONE>
 <*|TransformCompanyPhone|*PHONE>
 <*|TransformEmail|*LOWER>
  
 <*|Combine|*companyphone+mobile+email>
 <*|CombineLastCode|*True>
 <*|CombineField|*#companyphone>
 <*|CombineHTMLCode|*'<span class="highlight">T:&nbsp;</span><a href="tel:*|companyphone|*" style="color:#212121;text-decoration:none;text-underline:none"><span class="phone">*|companyphone|*</span></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'>
 <*|CombineField|*#mobile>
 <*|CombineHTMLCode|*'<span class="bar">|</span>&nbsp;&nbsp;<span class="highlight">M:&nbsp;</span><a href="tel:*|mobile|*" style="color:#212121;text-decoration:none;text-underline:none"><span class="phone">*|mobile|*</span></a>&nbsp;&nbsp;'>
 <*|CombineField|*#email>
 <*|CombineHTMLCode|*'<span class="bar">|</span>&nbsp;&nbsp;<span class="highlight">E:&nbsp;</span><a href="mailto:*|email|*" style="color:#212121;text-decoration:none;text-underline:none"><span class="phone">*|email|*</span></a>&nbsp;&nbsp;'> 
 
 
-->

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<meta name="date" content="2020-03-03T08:00:00+10:00">
<meta name="format-detection" content="telephone=no">

<!--[if gte mso 7]><xml>
  <o:OfficeDocumentSettings>
  <o:AllowPNG/>
  <o:PixelsPerInch>96</o:PixelsPerInch>
  </o:OfficeDocumentSettings>
</xml><![endif]-->

<title></title>

<style>
@font-face
	{font-family:"Calibri Light";
	panose-1:2 15 3 2 2 2 4 3 2 4;
	mso-font-charset:0;
	mso-generic-font-family:swiss;
	mso-font-pitch:variable;
	mso-font-signature:-536859905 -1073732485 9 0 511 0;}
@font-face
	{font-family:"Arial";
	panose-1:2 11 10 4 2 1 2 2 2 4;}
@font-face
	{font-family:"Arial Black";
	panose-1:2 11 10 4 2 1 2 2 2 4;}	
span.name
	{
	font-family:*|DefaultFont|*;
	color:*|TextColorHighlight|*;
	text-transform:uppercase;
	font-weight:bold;
	}
span.title
	{
	font-family:*|DefaultFont|*;
	color:*|TextColor|*;
	}
span.bar
	{
	color:*|BarColor|*;
	font-weight:bold;
	}
span.phone
	{
	font-size:*|DefaultFontSize|*;
	font-family:*|DefaultFont|*;
	font-weight:Normal;
	}
span.address
	{
	font-size:*|DefaultFontSize|*;
	font-family:*|DefaultFont|*;
	font-weight:Normal;
	}
span.emailhighlight
	{
	font-size:*|DefaultFontSize|*;
	font-family:*|DefaultFont|*;
	color:*|TextColorHighlight|*;
	font-weight:bold;
	}
span.email
	{
	font-size:*|DefaultFontSize|*;
	font-family:*|DefaultFont|*;
	color:#212121;
	text-decoration:none;
	text-underline:none;
	text-decoration:none;
	text-line-through:none;
	}
span.wwwhighlight
	{
	font-size:*|DefaultFontSize|*;
	font-family:*|DefaultFont|*;
	color:*|LinkWWWColor|*;
	text-decoration:none;
	text-underline:none;
	text-decoration:none;
	text-line-through:none;
	}
span.www{
	text-decoration:none;
	text-underline:none;
	}
span.socialicons
	{
	text-decoration:none;
	text-underline:none;
	text-decoration:none;
	text-line-through:none;
	}
span.footer
	{
	font-family:Arial,sans-serif;
	font-size:7.5pt;
	color:*|TextFooterColor|*;
	font-style:italic;
	}
span.highlight{
	font-family:*|DefaultFont|*;
	color:#002856;
	font-weight:bold;
	}
tr.hidden 
	{
	display: none;
	}
span.extra
	{
	font-size:*|DefaultFontSize|*;
	font-family:*|DefaultFont|*;
	color: Red;
	text-decoration:none;
	text-underline:none;
	text-decoration:none;
	text-line-through:none;
	}
span.xmas
	{
	font-size:10.0pt;
	font-family:*|DefaultFont|*;
	font-style: italic;
	color:#666666; 
	text-decoration:none;
	text-underline:none;
	text-decoration:none;
	text-line-through:none;
	}
table.normal
	{
	font-family:*|DefaultFont|*;
	font-size:*|DefaultFontSize|*;
	font-style: normal;
	}
tr.hidden 
	{
	display: none;
	line-height:0px;
	font-size:0px;
	height:0px;
	margin:0;
	padding:0;
	}

/* ExternalClass is used for Outlook.com hotmail.com */	
.ExternalClass * {line-height: 100%} 

</style>
</head>

<body lang=EN-AU style='tab-size:36.0pt'>
<div class="WordSection1" >
<table class="MsoNormalTable" border="0" cellspacing="0" cellpadding="0" width="100%" style='width:100.0%;border-collapse:collapse;mso-yfti-tbllook:1184;mso-padding-alt:0cm 0cm 0cm 0cm'>
<tr>
	<td width="100%" style='width:100.0%;padding:0cm 0cm 0cm 0cm'>
		<table class="MsoNormalTable" border="0" cellspacing="0" cellpadding="0" width="600" style='width:450pt;border-collapse:collapse;mso-yfti-tbllook:1184;mso-padding-alt:0cm 0cm 0cm 0cm'>
			<tr style='height:28px'>
				<td width="100%" style='width:100.0%;padding:0cm 0cm 0cm 0cm;height:28px'>
					<p class="MsoNormal" style='line-height:106%'>
						<span class="name">*|name|*,&nbsp;</span><span class="title"><i>*|title|*</i></span>
					</p>
				</td>
			</tr>
			<tr>				
				<td width="100%" style='width:100.0%;padding:0cm 0cm 0cm 0cm'>
					<p class="MsoNormal" style='line-height:106%'>
						<span class="phone">*|companyphone|*</span>
					</p>						
				</td>
			</tr>
			<tr>
				<td width="100%" style='width:100.0%;padding:0cm 0cm 0cm 0cm'>
					<p class="MsoNormal" style='line-height:106%'>
						<span class="emailhighlight">E&nbsp;</span><a href="mailto:*|email|*"><span class="email">*|email|*</span></a>
					</p>
				</td>
			</tr>
			<tr style='height:21.0pt'>
				<td width="100%" style='width:100.0%;padding:0cm 0cm 0cm 0cm'>
					<p class="MsoNormal" style='line-height:106%'>
						<span class="address">*|address|*</span>
					</p>					
				</td>
			</tr>
			<tr>
				<td width="100%" style='width:100.0%;padding:0cm 0cm 0cm 0cm'>
					<p class="MsoNormal" style='line-height:106%'>
						<span class="wwwhighlight"><a href="HTTPS://*|webpage|*"><b><span style='font-family:*|DefaultFont|*;color:*|LinkWWWColor|*;text-decoration:none;text-underline:none'>*|webpage|*</span></b></span></a>
					</p>
				</td>
			</tr>
			<tr class="*|socialicons_v|*" style='height:28.5pt'>
				<td style='padding:0cm 0cm 0cm 0cm;height:28.5pt'> 
					<div>
					<p class="MsoNormal" style='line-height:106%;vertical-align:middle'>
						<a href="*|YouTubeLink|*"><span class="socialicons">
							<img src="*|YouTube|*" alt="*|YouTubeAlt|*" width="22" height="22" border="0">
						</span></a>
					</p>
					</div>
				</td>
			</tr>
			<tr class="*|extranote_v|*">
				<td style='padding:0cm 0cm 0cm 0cm'></td>
					<p class="MsoNormal">
						<span class="extra">*|extranote|*</span>
					</p>	
				</td>
			</tr>
			<tr class="*|xmastext_v|*">
				<td style='padding:0cm 0cm 0cm 0cm'></td>
					<p class="MsoNormal">
						<span class="xmas">*|xmastext|*</span>
					</p>	
				</td>
			</tr>
			<tr style='height:170.25pt'>
				<td width="593" style='width:444.75pt;padding:0cm 0cm 0cm 0cm;height:170.25pt'>
					<p class="MsoNormal" style='line-height:106%'>
						<a href="https://*|webpage|*"><span class="www"><img width="593" height="227" border="0" src="*|imagename|*" alt="*|Company|*"/></span></a>
					</p>
				</td>
			</tr>
			</tbody>
			</table>
			<table class="normal" border="0" cellspacing="0" cellpadding="0" width="100%" style='width:100.0%;border-collapse:collapse;'>
			<tr>	
				<td style='padding:0cm 0cm 0cm 0cm'>
					<p class="MsoNormal" style='line-height:95%'>
						<span class="footer">*|footertext|*</span>
					</p>
				</td>
			</tr>
		</table>	
	</td>
</tr>
</table>
<p class="MsoNormal"><o:p>&nbsp;</o:p></p>
<p class="MsoNormal"><o:p>&nbsp;</o:p></p>
</div>
</body>
</html>
